app/controllers/home.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
    Home controller
    ~~~~~~~~~~~~~~~
    The home controller.

    :author: Jeff Kereakoglow
    :date: 2014-11-05
    :copyright: (c) 2014 by Alexis Digital
    :license: MIT, see LICENSE for more details
"""
from flask import Blueprint, render_template
from app.utils import cache_data, fetch_cached_data

mod = Blueprint("home", __name__)

@mod.route('/', methods=["GET"])
def home():
    """
    Renders the view for the home controller.

    :returns: HTML
    :rtype: flask.Response
    """
    # Prevent caching if in debug mode.
    return render_template("home.html", title="Home")

    # Check for a cached response
    rv = fetch_cached_data()

    if rv is not None:
        return rv

    out = render_template("home.html", title="Home")

    # Automatically cached for 15 minutes
    cache_data(out)

    return out

@mod.route('/about', methods=["GET"])
def about():
    """
    Renders the view for the home controller.

    :returns: HTML
    :rtype: flask.Response
    """
    # Prevent caching if in debug mode.
    return render_template("about.html", title="Login")

@mod.route('/login', methods=["GET"])
def login():
    """
    Renders the view for the home controller.

    :returns: HTML
    :rtype: flask.Response
    """
    # Prevent caching if in debug mode.
    return render_template("login.html", title="Login")

app/controllers/private.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
    Private controller
    ~~~~~~~~~~~~~~~
    The private controller.

    All public pages of the application ought to be controlled through this
    file.

    :author: Jeff Kereakoglow
    :date: 2014-11-06
    :copyright: (c) 2015 by Alexis Digital
    :license: MIT, see LICENSE for more details
"""
from flask import Blueprint, render_template
from app.utils import cache_data, fetch_cached_data
from flask_user import current_user, login_required

mod = Blueprint("private", __name__)
args = {"title":'',
        "stylesheet":'',
        "active_page":'',
        "show_header":True}

@mod.route('/dashboard', methods=["GET"])
@login_required
def dashboard():
    """
    Renders the view for the home controller.

    :returns: HTML
    :rtype: flask.Response
    """

    args["title"] = "Dashboard"
    args["active_page"] = "dashboard"
    args["stylesheet"] = "dashboard"
    args["show_header"] = "private"

    # Prevent caching if in debug mode.
    return render_template("private/dashboard.html", args=args)

    # # Check for a cached response
    # rv = fetch_cached_data()
    #
    # if rv is not None:
    #     return rv
    #
    # out = render_template("home.html", args=args)
    #
    # # Automatically cached for 15 minutes
    # cache_data(out)
    #
    # return out

@mod.route('/profile', methods=["GET"])
@login_required
def profile():
    """
    Renders the view for the home controller.

    :returns: HTML
    :rtype: flask.Response
    """

    args["title"] = "Profile"
    args["active_page"] = "profile"
    args["stylesheet"] = "about"
    args["show_header"] = True

    # Prevent caching if in debug mode.
    return render_template("private/profile.html", args=args)

app/controllers/public.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
    Public controller
    ~~~~~~~~~~~~~~~
    The public controller.

    All public pages of the application ought to be controlled through this
    file.

    :author: Jeff Kereakoglow
    :date: 2014-11-05
    :copyright: (c) 2015 by Alexis Digital
    :license: MIT, see LICENSE for more details
"""
from flask import Blueprint, render_template
from app.utils import cache_data, fetch_cached_data

mod = Blueprint("public", __name__)

args = {"title":'',
        "stylesheet":'',
        "active_page":'',
        "show_header":True}

@mod.route('/', methods=["GET"])
def home():
    """
    Renders the view for the home controller.

    :returns: HTML
    :rtype: flask.Response
    """

    args["title"] = "Home"
    args["active_page"] = "Home"
    args["show_header"] = "public"

    # Prevent caching if in debug mode.
    return render_template("public/home.html", args=args)

    # # Check for a cached response
    # rv = fetch_cached_data()
    #
    # if rv is not None:
    #     return rv
    #
    # out = render_template("home.html", args=args)
    #
    # # Automatically cached for 15 minutes
    # cache_data(out)
    #
    # return out

@mod.route('/about', methods=["GET"])
def about():
    """
    Renders the view for the home controller.

    :returns: HTML
    :rtype: flask.Response
    """
    args["title"] = "About"
    args["active_page"] = "about"
    args["stylesheet"] = "about"
    args["show_header"] = "public"

    # Prevent caching if in debug mode.
    return render_template("public/about.html", args=args)

app/templates/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
    Templates
    ~~~~~~~~~

    The templates module.

    The templates module is a default for Flask. Ideally, this module would be
    named "views" to stay in-line with model, view, controller naming scheme.

    :author: Jeff Kereakoglow
    :date: 2014-11-05
    :copyright: (c) 2015 by Alexis Digital
    :license: MIT, see LICENSE for more details
"""

app/templates/_layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="My starting point for Flask applications">
    <meta name="author" content="Jeff Kereakoglow">
    <link rel="icon" href="{{url_for('static', filename='favicon.ico')}}">

    <title>{{ config["APP_NAME"] }}{% if args.title %}  - {{ args.title }}{% endif %}</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    {% if args.stylesheet %}
    <link href="{{url_for('static', filename='css/'+args.stylesheet)}}.css" rel="stylesheet">
    {% endif %}
    <link href="{{url_for('static', filename='css/search')}}.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block header_js %}{% endblock %}
  </head>
  <body>
    {% if args.show_header %}
    {% include "header.html" %}
    {% endif %}

    {% block jumbotron %}{% endblock %}
    <div class="container">
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          <ul class="alert alert-info" role="alert">
          {% for message in messages %}
            <li>{{ message }}</li>
          {% endfor %}
          </ul>
        {% endif %}
      {% endwith %}
      {% block content %}{% endblock %}
      {% block footer %}{% endblock %}
    </div> <!-- /container -->
    <!-- Scripts -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    {% if current_user.is_authenticated() %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.10.4/typeahead.bundle.min.js"></script>
    <script src="../static/js/search.js"></script>
    {% endif %}
    {% block footer_js %}{% endblock %}
  </body>
</html>

app/templates/about.html
{% extends "layout.html" %}

{% block css %}
  <link href="../static/css/about.css" rel="stylesheet">
{% endblock %}

{% block header %}{% include "header.html" %}{% endblock %}

{% block content %}
  <div class="about">
    <h1>Flask Skeleton</h1>
    <p class="lead">Here's an example of a simple, text-only page</p>
    <p>
      This page is using <a href="http://getbootstrap.com/examples/starter-template/" target="_blank">Bootstrap's starter template</a>.
    </p>
  </div>
{% endblock %}

{% block footer %}{% include "footer.html" %}{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="My starting point for Flask applications">
    <meta name="author" content="Jeff Kereakoglow">
    <link rel="icon" href="../static/favicon.ico">

    <title>Flask Skeleton::{{ args.title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">

    {% if args.stylesheet %}
    <link href="../static/css/{{args.stylesheet}}.css" rel="stylesheet">
    {% endif %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block header_js %}{% endblock %}
  </head>
  <body>
    {% if args.show_header %}
    {% include "header.html" %}
    {% endif %}

    {% block jumbotron %}{% endblock %}
    <div class="container">
      {% block content %}{% endblock %}
      {% block footer %}{% endblock %}
    </div> <!-- /container -->
    <!-- Scripts -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    {% block footer_js %}{% endblock %}
  </body>
</html>

app/templates/footer.html
  <!-- footer.html -->
  <hr>
  <footer>
    <p>&copy; Your Company 2015</p>
  </footer>

app/templates/header.html
  <!-- header.html -->
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for("public.home")}}">{{config["PROJECT_NAME"]}}</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">

          {% set navigation_bar = [
          (url_for("public.home"), 'home', 'Home'),
          (url_for("public.about"), 'about', 'About')
      ] -%}
      {% set active_page = args.stylesheet|default('home') -%}

          <ul class="nav navbar-nav">
          {% for href, id, caption in navigation_bar %}
            <li{% if id == active_page %} class="active"{% endif
            %}><a href="{{ href|e }}">{{ caption|e }}</a></li>
          {% endfor %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated() %}
              <li class="dropdown">
              <a href="{{ url_for("private.profile") }}" class="dropdown-toggle" data-toggle="dropdown">{{ current_user.first_name }} <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for("private.profile") }}">Profile</a></li>
              </ul>
            </li>
              <li><a href="{{ url_for("private.dashboard") }}">Dashboard</a></li>
              <li><a href="{{ url_for("user.logout") }}">Log out</a></li>
            {% else %}
              <li><a href="{{ url_for("user.login") }}">Log in</a></li>
            {% endif %}
          </ul>
          {% if current_user.is_authenticated() %}
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control typeahead" placeholder="Search for a country...">
          </form>
          {% endif %}
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/templates/home.html
  {% extends "layout.html" %}
  {% block header %}{% include "header.html" %}{% endblock %}
  <!-- home.html -->
  {% block jumbotron %}
  <div class="jumbotron">
    <div class="container">

      <h1>It worked!</h1>
      <p>This template is being rendered from.<code>templates/home.html</code>. If you haven't already guessed, this application uses <a href="http://getbootstrap.com" target="_blank"> Bootstrap</a>. This particular template is <a href="http://getbootstrap.com/examples/jumbotron/" target="_blank">Bootstrap's jumbotron</a>.</p>
      <p><a class="btn btn-primary btn-lg" href="https://github.com/jkereako/flask-skeleton" target="_blank" role="button">Project on Github &raquo;</a></p>
    </div>
  </div>
  {% endblock %}

  {% block content %}
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-4">
      <h2>Caching</h2>
      <p>If you make a change to the source, reload, and don't see your change, it's because Flask's cahcing mechanism, SimpleCache, is activated. The cache is volitle and will not persist between runnings. The quick solution is to restart your server.</p>
      <p><a class="btn btn-default" href="http://flask.pocoo.org/docs/0.10/patterns/caching/" target="_blank" role="button">Caching docs &raquo;</a></p>
    </div>
    <div class="col-md-4">
      <h2>Flask User</h2>
      <p>This project supports user registration by default by way of <a href="https://github.com/lingthio/Flask-User" target="_blank">Flask-User</a>. If your project doesn't require user registration, remove it.</p>
      <p><a class="btn btn-default" href="http://pythonhosted.org/Flask-User/" target="_blank" role="button">Flask User docs &raquo;</a></p>
   </div>
    <div class="col-md-4">
      <h2>Templates</h2>
      <p>Flask uses Jinja as its templating engine because both technologies were written by the same guy. Get familiar with it.</p>
      <p><a class="btn btn-default" href="http://jinja.pocoo.org/docs/dev/templates/" target="_blank" role="button">Jinja docs &raquo;</a></p>
    </div>
  </div>

  {% endblock %}
  {% block footer %}{% include "footer.html" %}{% endblock %}

app/templates/login.html
  {% extends "layout.html" %}

  {% block css %}
    <link href="../static/css/login.css" rel="stylesheet">
  {% endblock %}

  {% block content %}
  <form class="form-signin" role="form">
    <h2 class="form-signin-heading">Please sign in</h2>
    <input type="email" class="form-control" placeholder="Email address" required autofocus value="admin@me.com">
    <input type="password" class="form-control" placeholder="Password" required value="password">
    <div class="checkbox">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
  </form>
  {% endblock %}